### ISSUE TITLE
External Storage Mapping

### ISSUE THREAD

**Issue by RealDeclan** [thilojaeggi/WinGetty#15]
**Is your feature request related to a problem? Please describe.**
I have this running in an app service in azure. I cant map the storage location to an external store. 

**Describe the solution you'd like or how it could be implemented**
I would like to store the installers and manifests to a bucket like an Azure Storage Account. This could also act as a recovery point should the app fail. It could be pointed to the data store and find all the manifests and apps without having to re-add them.

**Comment by thilojaeggi** [comment]
I see no reason why you shouldn't be able to store your packages in an Azure service, just modify your docker-compose file for both WINGETTY_DATABASE_URI and the volumes.

**Comment by RealDeclan** [comment]
I've gone down the route of attaching a Azure File Share to the instance. If i get it working, ill report back with the solution.

**Comment by RealDeclan** [comment]
Ok, works great. In short, i have deployed Wingetty to an Azure App Service. I then created a storage account with an Azure File share. Once both are created, i attached the Azure File Share to the App service and mapped the file share paths as follows 
![image](https://github.com/thilojaeggi/WinGetty/assets/81355373/582e4431-5395-4032-a4b7-b3db7d6556a3)
