### ISSUE TITLE
Wingetty over Dns record

### ISSUE THREAD

**Issue by BouuuuuuH** [thilojaeggi/WinGetty#17]
Hello,

We just have a fresh install of wingetty, this seems cool. We have configured nginx as reverse proxy and we can now add our source on winget client. Our wingetty is on a specific computer over our DNS, the computer name is “repository”. To use https we are using our wildcard certificate (like *.contoso.com) and register the computer with a dns record (repository.contoso.com). So, we can add our source like that: 
“winget source add -n WinGetty -t "Microsoft.Rest" -a https://repository.contoso.com /wg/”
Everything works fine, and source can be list: 
 
![image](https://github.com/thilojaeggi/WinGetty/assets/101139318/bb48ad11-6cda-4e5d-958e-9ff0075eb124)

And my package for the test can be “search”
 
![image](https://github.com/thilojaeggi/WinGetty/assets/101139318/be9660c2-31c5-49d9-ab08-a45944c17a18)

But when I want to install it:
 
![image](https://github.com/thilojaeggi/WinGetty/assets/101139318/d241ebeb-6885-42b0-8ead-ded15a92c569)

As you can see on the screen capture, the URL returned is not the good one, and we cannot download. The process stays stuck at this point. We assume that is normal, because wingetty cannot know our dns record, but do you have a setting to set this information, to fix download part?
To be clear if, with my browser, I go to https://repository.contoso.com/api/download/Publisher.TestPackage/1.1/x86/user download start and succeed.

Thanks a lot,
Thomas.

**Comment by thilojaeggi** [comment]
So I've just read up on this.
This could be due to a misconfigured reverse proxy but mitht be fixable by setting WINGETTY_SERVER_NAME with the domain including the port, so 443.

**Comment by BouuuuuuH** [comment]
Thanks for you .conf file, it works pretty fine with it. We can add source, install package, and all of that using https.

Just one point is not working on https, and not a big deal for us, we cannot add package on https, only using http://repository:8080 web interface. Is that a known problem ? or again a missconfiguration on our side ?

**Comment by thilojaeggi** [comment]
That's quite a weird issue, any error output when that happens in the browser console or in the container?

**Comment by BouuuuuuH** [comment]
Right, console talks about "413 (Payload too large)" so I increase client_max_body_size on nginx.conf

Everything is working now. Thanks a lot for your time.
