### ISSUE TITLE
Worker Timeout with Large Package

### ISSUE THREAD

**Issue by ImNtReal** [thilojaeggi/WinGetty#20]
**Describe the bug**
I'm trying to upload a nested installer that is a hefty 2.4 GB. Nothing seems to happen in the GUI once the upload is complete, but I see a message in the log like: `[1] [CRITICAL] WORKER TIMEOUT`

**To Reproduce**
1. Click Add Package
2. Fill out form, and select an installer that's large enough to trigger the timeout
3. Wait
4. See error in log

**Expected behavior**
Package is generated and available for install.

**General Information:**
 - WinGetty Version 0.0.4

**Additional context**
Just having a way to adjust the timeout for the worker process might be enough to take care of this one.

**Comment by kdpuvvadi** [comment]
Noticied same thing with smaller packages also `[1] [CRITICAL] WORKER TIMEOUT (pid:11)` package size was around 25Mb.

**Comment by thilojaeggi** [comment]
I've switched to the gevent worker for gunicorn now and tried some larger files without issues, keen on hearing if it is fixed for you as well?

**Comment by ImNtReal** [comment]
I'm still seeing worker timeouts with my large package in 0.0.8. It's a nested package, so if the process includes unzipping it, that could be where it's timing out.

**Comment by ImNtReal** [comment]
Or is it a hash?
