### ISSUE TITLE
Problems with starting Wingetty

### ISSUE THREAD

**Issue by Narrowcastingscherm** [thilojaeggi/WinGetty#28]
I am trying now to install wingetty on a alma linux server, but every time i run docker-compose up -d the systems freezes and i cannot connect to 8080, this is only when i run the wingetty docker compose command

**Comment by thilojaeggi** [comment]
Any logs on the system side, this sounds more like an issue with your environment than with WinGetty itself.

**Comment by Narrowcastingscherm** [comment]
can i go back to an older version to try it?

**Comment by thilojaeggi** [comment]
You can just choose an older docker image with for example: ghcr.io/thilojaeggi/wingetty:0.0.5
You'd need to delete the created volumes though (if they were even created).
