### ISSUE TITLE
Problems with postgres as db server

### ISSUE THREAD

**Issue by hschmidt-dev** [thilojaeggi/WinGetty#31]
I try to setup wingetty using postgres 16 container as db server. There seem to be 2 problems:
1. Python module psycopg2-binary is missing in requirements.txt
2. Authentication against db server does not work with error message: "fe_sendauth: no password supplied"

I added the password using WINGETTY_SECRET_KEY variable. But this seems not to be used for db server authentication.

**Comment by thilojaeggi** [comment]
The credentials needs to be provided in the connection uri like so `postgresql+psycopg2://scott:tiger@localhost:5432/mydatabase`.
This will not work in the current version though as it's lacking pyscopg2-binary, will work in v0.0.8 though.

**Comment by thilojaeggi** [comment]
Should work now in v0.0.8

**Comment by thilojaeggi** [comment]
Were you able to test it yet?
