### ISSUE TITLE
Wingetty name in header

### ISSUE THREAD

**Issue by Narrowcastingscherm** [thilojaeggi/WinGetty#35]
I have wingetty running in a docker container on a Synology, i want to know where can i change the name wingetty that is in the header on the page, want to change the name to company name together with a logo.

**Comment by eujoanderson** [comment]
You need to access the container using docker, which would be something like this:
docker exec -it wingtty bash

After that, access the path:
vim /app/templates/nav.j2

Then just go to line 9 of this nav.j2 file and change the Wingetty name to whatever you want:
   <span class="font-semibold text-2xl {% if config.IS_CLOUD %}text-lg leader-5{% endif %} tracking-tight mb-0.5"> < WinGetty > {% if config.IS_CLOUD %}< br>
