### ISSUE TITLE
Nested Installers

### ISSUE THREAD

**Issue by ImNtReal** [thilojaeggi/WinGetty#4]
**Is your feature request related to a problem? Please describe.**
I have a package that features a .exe installer nested inside of a .zip file. It would be handy if WinGetty had an advanced option for this, or if there's a way for me to supply it manually via an API, that would be good to know.

**Describe the solution you'd like or how it could be implemented**
Have an option on the Add Package dialog to have a nested package type with a relative path to the installer.

**Describe alternatives you've considered**
I honestly haven't dug into the API yet, to see if it's possible for me to submit a package that way, but I'm guessing it probably is a part of the spec.

**Additional context**
Not sure what else to add. The YAMLCreate.ps1 script in the winget-pkgs repo has support for this, so that could be helpful to reference.

**Comment by thilojaeggi** [comment]
Just added preliminary support for this.

If you want, you can try it out with your own package on https://wingetty.thilojaeggi.ch with the login demo@demo.com:demo.
I already added postman this way for testing and it seems to work fine:
<img width="1459" alt="Screenshot 2023-07-10 at 22 58 13" src="https://github.com/thilojaeggi/WinGetty/assets/20727326/164d7b98-0350-456b-a508-a233c37673b7">

<img width="671" alt="Screenshot 2023-07-10 at 22 55 20" src="https://github.com/thilojaeggi/WinGetty/assets/20727326/cb0b493d-117c-4885-bbef-8cf965a9b739">

**Comment by ImNtReal** [comment]
Sorry. I didn't realize you'd given me a place to test. I don't actually have access to that site from my work network (which is where my package is).

Let's go ahead and close this out, and I'll open a new bug once you've released if I have an issue specific to my package.

**Comment by thilojaeggi** [comment]
v0.0.3 is out now featuring nested installers.
