### ISSUE TITLE
wingetty.dev requires secure connection, but submits wrong certificates

### ISSUE THREAD

**Issue by andreimirt** [thilojaeggi/WinGetty#42]
**Describe the bug**
When clicking on any of the [wingetty.dev](wingetty.dev) links on this repository, the website cannot be accessed due to wrongly configured certificates on the server.

**To Reproduce**
1. Go to [wingetty.dev](wingetty.dev)
2. See browser error about wrongly configured certificates for wingetty.dev

**Expected behavior**
No content blocking errors when visiting [wingetty.dev](wingetty.dev).

**Screenshots**
![Screenshot 2024-02-22 102646](https://github.com/thilojaeggi/WinGetty/assets/44326744/005b2709-d9e3-49c1-bc2a-ec430d094c86)

**General Information:**
 - OS: Windows (but really, any)
 - Browser [Firefox, chrome, edge, vivaldi, and I assume all others] (if website related)
 - WinGetty Version [N/A]

**Additional context**
If the issue is that the website does not exist, so there wouldn't be a point to configure proper certificates yet, then the fix for this bug is for the links to wingetty.dev on the repository to be removed.
Congrats on this useful and cool project. In my opinion it likely loses many users on the account of trust due to issues like this.

**Comment by thilojaeggi** [comment]
Seems to me that it's fixed now, closing.
