### ISSUE TITLE
Run Script (.ps1 or .cmd) to run a SW installation

### ISSUE THREAD

**Issue by Brickleton** [thilojaeggi/WinGetty#47]
Hello,

I am looking for an option to preferably run PowerShell or batch scripts for the installation. The background to this is that I would like to test whether I can implement the configurations relevant to my work during a software installation. For this we use scripts that trigger the installation of the software, but also implement other things, such as copying a .config file or removing desktop shortcuts. Is something like this currently possible? If not, would it be possible to include this in a future release?

Many thanks for your efforts

Kevin

**Comment by thilojaeggi** [comment]
I think this should work already if you use the "nested" installer type and specify ./setup.ps1, I'm unsure if winget allows you to actually modify user data with this script though like editing the Desktop.
Under nested installer you also need to select the installer type of the nested installer, you could experiment around with the options.

**Comment by Brickleton** [comment]
And would it be possible to run a .cmd file? When I add the .cmd file as I added the .ps1 the installation failures every time.

**Comment by thilojaeggi** [comment]
I assume also not due to winget not officially supporting this.

**Comment by Brickleton** [comment]
Alright then thank you for your support, i will keep an eye on wingetty, its a very cool project. I will cloese this issue with this comment
