### ISSUE TITLE
Why doesn't the https 8443 port appear or add it to the package urls?

### ISSUE THREAD

**Issue by eujoanderson** [thilojaeggi/WinGetty#53]
Wingetty is running on port 8443 with redirection with nginx but some requests from the application itself do not show the port that runs on https.
![Captura de tela 2024-04-23 122227](https://github.com/thilojaeggi/WinGetty/assets/82622160/b3c49d44-a82d-46d4-8142-5cf4c2a47e0a)

![Captura de tela 2024-04-23 122335](https://github.com/thilojaeggi/WinGetty/assets/82622160/35697867-a42e-4fee-9da5-8dc34c593422)

**Comment by thilojaeggi** [comment]
This must be a misconfiguration in your NGINX reverse proxy as it is included in my case for example.
You could also give setting the env variable SERVER_NAME a go and setting that to "wingetty.shop:8443" respectively
