### ISSUE TITLE
Incorporate everything into Docker Compose file

### ISSUE THREAD

**Issue by amcco1** [thilojaeggi/WinGetty#6]
Hey thilo, this looks like a great tool, thanks for making it!

I have one request for simplifying the installation. Could you incorporate everything needed into a single docker-compose file? 

I love to use Portainer and  I hate when I have to clone a git repo and then run it with docker. 

Would you be willing to incorporate everthing needed into the docker image, then could just add a mysql container into the compose file. 

Could literally just copy and paste the docker compose file and edit the variables then and be up in running within minutes, without having to clone the repo.

**Comment by thilojaeggi** [comment]
You don't have to clone the repo, the docker-compose file references the latest stable image.
https://github.com/thilojaeggi/WinGetty/blob/main/docker-compose.yml

**Comment by amcco1** [comment]
Thanks! I was able to get it up and running with a few small modifications to the compose file.  However I have run into a real issue.
 
When I try to add a package with a name longer than 20 characters it has an error that says [object Object]

![Screenshot 2023-07-27 112412](https://github.com/thilojaeggi/WinGetty/assets/58500201/7da539c1-28fb-4ffc-b18e-d00c7890ba33)

If the package identifier is 20 characters or shorter, it works like a charm. But if its 21+ characters it gives the object object error.

**Comment by thilojaeggi** [comment]
I see you're running version 0.0.3 which is still in development, if you use the tag "stable" version 0.0.2 gets pulled which should work.
You'll have to recreate the database though, since there are some changes between 0.0.2 and 0.0.3

**Comment by amcco1** [comment]
I am using the stable tag in my compose file. 

![Screenshot 2023-07-27 131326](https://github.com/thilojaeggi/WinGetty/assets/58500201/b63ec3b3-bc2f-4c5e-b953-0af5e6524e08)

**Comment by amcco1** [comment]
Yes that worked, and v0.0.2 does not have the issue with id character length. 

Strange that the latest tag is not pulling the correct version.

**Comment by thilojaeggi** [comment]
The current limitation of the identifier is 20 chars, will be upped in v0.0.3

**Comment by thilojaeggi** [comment]
@ImNtReal there is a stable tag though: https://github.com/thilojaeggi/WinGetty/pkgs/container/wingetty/106822412?tag=stable

**Comment by ImNtReal** [comment]
@thilojaeggi I didn't mean to imply that there wasn't. I just didn't know if OP had looked for one. :)

**Comment by thilojaeggi** [comment]
Ah, completely misunderstood that then. When looking at OP's screenshot they were using the stable tag though, although maybe they went from latest to stable without removing the "latest (dev)" image.
