### ISSUE TITLE
Ability to block unnecessary repositories

### ISSUE THREAD

**Issue by RingsOfSaturn** [thilojaeggi/WinGetty#64]
I'd like to use only my repository within the department. But I would not want to allow the rest of my staff to include or add repositories from other sources.

Please add either a feature during installation that would allow you to select the desired repositories (.NET tool, Powershell 5.x, Chocolatey and etc.) Or ideally disallow changing application settings without administrative rights.

Thank you for your work!

**Comment by thilojaeggi** [comment]
As in within the Shell? Are you talking about the winget source add command?

**Comment by RingsOfSaturn** [comment]
> As in within the Shell? Are you talking about the winget source add command?

Sorry for the misunderstanding, I figured it out.
