### ISSUE TITLE
Upload failed - big packages 

### ISSUE THREAD

**Issue by kmsrockz** [thilojaeggi/WinGetty#7]
Hello,
first of all, thank you. Wingetty is awesome stuff!
Question:
Is there a maximum file size for uploading installation media?
For large .exe files over 1GB, the upload window disappears at 100%.

THX an greetz ✌️

**Comment by thilojaeggi** [comment]
I think that's one of the issues currently in 0.0.2 set to be fixed in version 0.0.3

**Comment by kmsrockz** [comment]
When will version 0.0.3 be released?
It will coming soon ? :D

**Comment by thilojaeggi** [comment]
Can't give an ETA yet cause I need to handle migrations between the versions cause 0.0.3 adds a permission system and some major overhauls in form validation and frontend updating.

**Comment by kmsrockz** [comment]
Thx, but now i cant upload any packages 🤣

Von: Thilo Jaeggi ***@***.***>
Datum: Donnerstag, 24. August 2023 um 12:21
An: thilojaeggi/WinGetty ***@***.***>
Cc: IT ***@***.***>, Author ***@***.***>
Betreff: Re: [thilojaeggi/WinGetty] Upload failed - big packages (Issue #7)

v0.0.3 is out now!

**Comment by thilojaeggi** [comment]
I just set up a new instance in Docker and it works for me? Do you see any error messages when running WinGetty with `docker compose up` omitting the -d?

**Comment by kmsrockz** [comment]
Nope it starts fine, but I have no upload button in wingetty window

Thx
R


Von: Thilo Jaeggi ***@***.***>
Datum: Freitag, 25. August 2023 um 09:30
An: thilojaeggi/WinGetty ***@***.***>
Cc: IT ***@***.***>, Author ***@***.***>
Betreff: Re: [thilojaeggi/WinGetty] Upload failed - big packages (Issue #7)

I just set up a new instance in Docker and it works for me? Do you see any error messages when running WinGetty with docker compose up omitting the -d?

**Comment by thilojaeggi** [comment]
Could you share a screenshot from the Users tab, I suspect you're somehow assigned to the user role and not the admin/user.
If you can, you could also just delete the database/volumes.

**Comment by kmsrockz** [comment]
That helps thanks, with first user was created, I have the upload button back ! Thank you !

But Unfortunately, uploading large files is still not possible.

Greetz
R


Von: Thilo Jaeggi ***@***.***>
Datum: Freitag, 25. August 2023 um 09:56
An: thilojaeggi/WinGetty ***@***.***>
Cc: IT ***@***.***>, Author ***@***.***>
Betreff: Re: [thilojaeggi/WinGetty] Upload failed - big packages (Issue #7)

Could you share a screenshot from the Users tab, I suspect you're somehow assigned to the user role and not the admin/user.
If you can, you could also just delete the database/volumes.

**Comment by amcco1** [comment]
Seeing the same problem here. Trying to upload a 175MB installer and it throws the same error. 
![Screenshot 2023-09-11 200353](https://github.com/thilojaeggi/WinGetty/assets/58500201/413b8e6d-70de-4383-9f13-0daef6ef4392)

**Comment by thilojaeggi** [comment]
This might be related to your NGINX configuration or even Cloudflare based on the error message.
I know my public facing instance running behind an NGINX reverse proxy has no issues.
I'll try to look into it though, mind sharing your setup?

**Comment by thilojaeggi** [comment]
Just checked, Cloudflare only allows 100 MB for Free and Pro, 200 MB for Business and 500 MB for Enterprise, you could try disabling/bypassing it by changing it to a grey cloud in the DNS settings.
