### ISSUE TITLE
Trouble Adding Any Packages (Probably my fault)

### ISSUE THREAD

**Issue by EtherMadness** [thilojaeggi/WinGetty#8]
Hi Thilo,

First of all, thank you and sorry to bug you.  This seems like an awesome tool and I'm excited to get it up and running!

I stood up my WinGetty v0.0.3 instance using Docker on Ubuntu 20.04.6 LTS, configured Nginx for reverse proxy, and successfully added the repo to Winget on my workstation.

I'm having trouble adding any packages to WinGetty at all.

When I upload a package, the progress bar completes, I get a message that says "Package Added Successfully" but no packages are listed and no packages are available in the repo from my workstation.  I've tried uploading a package using the public IP of the server:8080, the FQDN via the reverse proxy, and on the server itself using localhost:8080.

I looked for the /app/instance and /app/app/packages folders referenced in the docker-compose.yml in the WinGetty folder and didn't see them.  I then created the folders with permissions for everyone (chmod 777), but still no luck.

Is there logging somewhere that I can check to see I've done wrong?  Any assistance would be greatly appreciated.

Thank you.

**Comment by EtherMadness** [comment]
![image](https://github.com/thilojaeggi/WinGetty/assets/135036708/7ff8e91f-9f58-4084-a079-7ead3fb3ea33)

**Comment by thilojaeggi** [comment]
Looking into it, meanwhile, does version v0.0.2 (docker tag "stable") work for you?

**Comment by thilojaeggi** [comment]
Was an issue on my end, the db commited but the package didn't get added beforehand.
Will be fixed with the release of v0.0.3

**Comment by thilojaeggi** [comment]
v0.0.3 is out now!
