### ISSUE TITLE
Upgrade from 0.0.2 to 0.0.3 hasn't seemed to run migrations for me

### ISSUE THREAD

**Issue by ImNtReal** [thilojaeggi/WinGetty#9]
I had 0.0.2 up and running on a Kubernetes cluster. When I restarted to upgrade to 0.0.3, I got this:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: role
[SQL: SELECT role.id AS role_id, role.name AS role_name
FROM role
WHERE role.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('admin', 1, 0)]
```
I'm thinking that maybe the migrations need to run. Is there a way to kick them manually?

**To Reproduce**
1. Get 0.0.2 up and running with just a SQLite database
2. Shutdown the container
3. Start it back with the 0.0.3 image

**Expected behavior**
Database migrations should run, and make sure the databases are in the correct state.

**General Information:**
 - OS: k8s
 - WinGetty Version 0.0.3

**Comment by ImNtReal** [comment]
Sorry if you're not interested in supporting running it this way at this point. If you do want to, I'll be happy to share the manifest I'm using to get it up and running with you.

**Comment by ImNtReal** [comment]
I did spin 0.0.3 back up with a new database file, and that worked fine.

**Comment by thilojaeggi** [comment]
I'll look into it, it somehow worked perfectly fine for me.
For release v1.0.0 (whenever that happens) I'll make sure that these processes work better.

**Comment by ImNtReal** [comment]
Pretty sure this was actually caused by a file permission change I had made, and wasn't aware of (from copying the database elsewhere, and then later back). I was able to get my database upgraded with the flask command.
